apiVersion: v2
name: firefly-db
version: 0.2.1
description: Installs a postgres db for Firefly III
type: application
sources:
  -  https://coollision.github.io/helm-charts/firefly-db
maintainers:
  - name: coollision
    email: Coollision@users.noreply.github.com
