apiVersion: v2
name: k3s-monitoring
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.63.0"
kubeVersion: ">=1.16.0-0"
home: https://coollision.github.io/helm-charts/
maintainers:
  - name: coollision
    email: Coollision@users.noreply.github.com
dependencies:
  - name: kube-prometheus-stack
    version: 45.25.0
    repository: https://prometheus-community.github.io/helm-charts