apiVersion: v2
name: firefly-iii
version: 1.4.0
description: Installs Firefly III
type: application
home: https://www.firefly-iii.org/
sources:
  - https://github.com/firefly-iii/firefly-iii/
maintainers:
  - name: coollision
    email: Coollision@users.noreply.github.com
icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.github/assets/img/logo-small.png
