apiVersion: v2
name: firefly-iii-stack
version: 0.7.2
description: Installs Firefly III stack (db, app, importer)
type: application
dependencies:
- name: firefly-db
  version: 0.2.1
  condition: firefly-db.enabled
  repository: https://coollision.github.io/helm-charts/
- name: firefly-iii
  version: 1.4.0
  condition: firefly-iii.enabled
  repository: https://coollision.github.io/helm-charts/
- name: importer
  version: 1.3.1
  condition: importer.enabled
  repository: https://coollision.github.io/helm-charts/
home: https://coollision.github.io/helm-charts/
sources:
  - https://coollision.github.io/helm-charts/
maintainers:
  - name: coollision
    email: Coollision@users.noreply.github.com
icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.github/assets/img/logo-small.png
